name: Test xxh after push

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install xonsh
      run: pip install xonsh
    - name: Install xxh-dev
      run: |
        cd ..
        git clone --depth 1 https://github.com/xxh/xxh-dev
        cd xxh-dev
        pip install -r requirements.txt
    - name: xde build
      run: cd ../xxh-dev && ./xde build
    - name: xde up
      run: cd ../xxh-dev && ./xde up
    - name: xde test
      run: cd ../xxh-dev && ./xde test



