name: Build portable xxh

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install xonsh shell
      run: pip install xonsh
    - name: Build xxh-appimage
      run: xonsh xxh-appimage-build.xsh
    - name: Build xxh-portable-musl-alpine-build
      run: xonsh xxh-portable-musl-alpine-build.xsh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/xxh-x86_64.AppImage
          build/xxh-portable-musl-alpine-Linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
